version: "3.5"

services:
  tb :
    image: gaetanlandreau/pytorch:nvs
    build:
      context: .
      dockerfile: Dockerfile
      target: torch

    command: "tensorboard --logdir /data/logs/to/the/tensorboard --host 0.0.0.0"  
    ports:
      - 6809:6006 # For TensorBoard
    working_dir: /root/

    volumes:
     
      # Datadrive 
      - type: bind
        source: /data/datadrive/
        target: /data/

  main:
    image: gaetanlandreau/pytorch:nvs
    build:
      context: .
      dockerfile: Dockerfile
      target: torch

    restart: always
    shm_size: '4gb'
    
    command: "jupyter-lab --ip=0.0.0.0 --allow-root --no-browser"  
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 2
              capabilities: [gpu]
    ports:
      - 80:8888 # For JupyterLab 
    working_dir: /root/

    environment:
      - AWS_PROFILE=rd
      - PASSWORD=password
    
    volumes:
      
      # SHR-NERF
      - type: bind
        source: /home/SHR-NeRF/
        target: /root/SHR-NeRF/
        
      # Datadrive 
      - type: bind
        source: /data/datadrive/
        target: /data/